### ISSUE TITLE
I am not sure but I think its not downloading any attachments does it?

### ISSUE THREAD

**Issue by hitswa** [theringe/gmail-backup-com-alter#1]
I was trying complete backup solution... but I don't think that it does download attachments

**Comment by theringe** [comment]
there are attachments in my recently backup

**Comment by hitswa** [comment]
which one is recent

**Comment by hitswa** [comment]
I don't find any attachment...

**Comment by hitswa** [comment]
Okay, I get it... It's in binary format inside emails only... Kudos...

**Comment by hitswa** [comment]
you can close the issue

**Comment by theringe** [comment]
ok
